---
name: Build synergy-serial-docker

on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the synergy-serial Docker image
        run: |
          docker build . --tag ghcr.io/mikeeq/synergy-serial:latest
          docker push ghcr.io/mikeeq/synergy-serial:latest
