---
name: Build synergy-serial-docker

on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the synergy-serial Docker image
        run: |
          docker build . --tag ghcr.io/mikeeq/synergy-serial:latest
          docker push ghcr.io/mikeeq/synergy-serial:latest

# Info: to push images to your top-level organizational registry, you need to allow it
# Repository --> Settings --> Actions --> General --> Workflow permissions --> Read and write permissions (choose) --> Save (click)
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions
